name: Build and Push Docker Image

on:
  push:
    branches:  
      - main
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
    - uses: actions/checkout@main
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "180489" --password-stdin
        docker image build -t 180489/pyDollyv2:latest .
        docker push 180489/pyDollyv2:latest

